import React, { useEffect, useState } from "react";
import { CARD_EVENT_TYPES, type CardEventType, type CardRule, type ManagedCard } from "../card-events/types";

type Config = { cards: ManagedCard[]; cardRules: CardRule[] };
const blankCard = (): ManagedCard => ({ id: `card_${Date.now()}`, name: "新卡片", description: "", category: "lighting", rarity: "common", image: "", hidden: false, enabled: true });
const blankRule = (cardId: string): CardRule => ({ id: `rule_${Date.now()}`, cardId, triggerType: "action", conditions: { action: "killEnemy", statKey: "action.killEnemy" }, requiredCount: 1, priority: 0, enabled: true });
const labels: Record<CardEventType, string> = { action: "遊戲行為", dialogue: "角色對話", areaVisit: "區域造訪", bossResult: "Boss 勝敗", quizAnswer: "答題結果", collectible: "收集物" };

export function CardEventAdmin() {
  const [config, setConfig] = useState<Config>({ cards: [], cardRules: [] });
  const [status, setStatus] = useState("載入卡片規則中…");
  const [saving, setSaving] = useState(false);
  useEffect(() => { fetch("/api/card-event-admin/config").then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error); setConfig({ cards: body.cards, cardRules: body.cardRules }); setStatus(body.source === "firebase" ? "已載入 Firebase 卡片規則" : "目前顯示預設規則；按儲存後會建立 Firebase 卡片資料"); }).catch((error) => setStatus(`無法載入：${error.message}`)); }, []);
  const setCard = (id: string, patch: Partial<ManagedCard>) => setConfig((current) => ({ ...current, cards: current.cards.map((card) => card.id === id ? { ...card, ...patch } : card) }));
  const setRule = (id: string, patch: Partial<CardRule>) => setConfig((current) => ({ ...current, cardRules: current.cardRules.map((rule) => rule.id === id ? { ...rule, ...patch } : rule) }));
  const save = async () => { setSaving(true); try { const response = await fetch("/api/card-event-admin/config", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(config) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setStatus("已儲存至 Firebase；新事件將立即使用這套規則。"); } catch (error) { setStatus(`儲存失敗：${error instanceof Error ? error.message : "未知錯誤"}`); } finally { setSaving(false); } };
  return <div className="admin-card-events"><div className="admin-card-event-toolbar"><div><b>Card Event System</b><small>{status}</small></div><button type="button" onClick={save} disabled={saving}>{saving ? "儲存中…" : "儲存卡片規則到 Firebase"}</button></div><p className="admin-card-event-note">前台只回報事件。伺服器會更新玩家 stats、比對相同 triggerType 的規則、排除已取得卡片，依 priority 只發放一張，其餘存入 pendingCards。</p><button type="button" className="admin-add" onClick={() => setConfig((current) => ({ ...current, cards: [...current.cards, blankCard()] }))}>＋ 新增卡片</button><div className="admin-stack">{config.cards.map((card) => { const rules = config.cardRules.filter((rule) => rule.cardId === card.id); return <details className="admin-record" key={card.id}><summary><b>{card.name}</b><span>{card.category}｜{rules.length} 條規則</span></summary><div className="admin-record-body two-col"><label>卡片名稱<input value={card.name} onChange={(event) => setCard(card.id, { name: event.target.value })} /></label><label>分類<input value={card.category} onChange={(event) => setCard(card.id, { category: event.target.value })} /></label><label className="wide">說明<textarea value={card.description} onChange={(event) => setCard(card.id, { description: event.target.value })} /></label><label className="admin-check"><input type="checkbox" checked={card.enabled} onChange={(event) => setCard(card.id, { enabled: event.target.checked })} />啟用卡片</label><label className="admin-check"><input type="checkbox" checked={card.hidden} onChange={(event) => setCard(card.id, { hidden: event.target.checked })} />隱藏卡</label><button type="button" className="admin-add" onClick={() => setConfig((current) => ({ ...current, cardRules: [...current.cardRules, blankRule(card.id)] }))}>＋ 新增規則</button><div className="wide admin-rule-list">{rules.map((rule) => <div className="admin-rule" key={rule.id}><b>觸發規則</b><label>事件類型<select value={rule.triggerType} onChange={(event) => setRule(rule.id, { triggerType: event.target.value as CardEventType })}>{CARD_EVENT_TYPES.map((type) => <option key={type} value={type}>{labels[type]}</option>)}</select></label><label>條件 JSON<textarea value={JSON.stringify(rule.conditions)} onChange={(event) => { try { setRule(rule.id, { conditions: JSON.parse(event.target.value) }); } catch {} }} /></label><label>累積門檻<input type="number" min="1" value={rule.requiredCount} onChange={(event) => setRule(rule.id, { requiredCount: Math.max(1, Number(event.target.value)) })} /></label><label>優先級<input type="number" value={rule.priority} onChange={(event) => setRule(rule.id, { priority: Number(event.target.value) })} /></label></div>)}</div></div></details>; })}</div></div>;
}
